version: '3.7'

services:
    minio:
        restart: always
        image: minio/minio
        container_name: mlflow_s3
        command: server /data --console-address ':9001' --address ':9000'
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - minio_data:/data
        ports:
            - "9001:9001"

    mc:
        image: minio/mc
        depends_on:
            - minio
        container_name: mc
        env_file:
            - .env
        entrypoint: >
            /bin/sh -c "
            /tmp/wait-for-it.sh minio:9000 &&
            /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
            /usr/bin/mc mb minio/mlflow;
            exit 0;
            "
        volumes:
            - ./wait-for-it.sh:/tmp/wait-for-it.sh

    db:
        restart: always
        image: mysql/mysql-server
        container_name: mlflow_db
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

    web:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
            - mc
            - db
        ports:
            - "5501:5000"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0
        
    ngrok_mlflow: 
        restart: always
        image: wernight/ngrok
        depends_on:
            - web
        ports:
            - 4040:4040
        environment: 
            - NGROK_AUTH=${NGROK_AUTHTOKEN}
            - NGROK_PROTOCOL=https
            - NGROK_BINDTLS=true
            - NGROK_PORT=web:5000
            - NGROK_USERNAME=${MLFLOW_USER}
            - NGROK_PASSWORD=${MLFLOW_PASSWORD}
    ngrok_minio: 
        restart: always
        image: wernight/ngrok
        depends_on:
            - web
        ports:
            - 4041:4040
        environment: 
            - NGROK_AUTH=${NGROK_AUTHTOKEN2}
            - NGROK_PROTOCOL=https
            - NGROK_BINDTLS=true
            - NGROK_PORT=minio:9000
    
volumes:
    dbdata:
    minio_data: